language: python
# use container-based infrastructure
sudo: false
python:
  - "3.5"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
 - pip install --upgrade setuptools
  # Install nidmresults from source in GitHub repo
 - pip install --upgrade --no-deps git+https://github.com/cmaumet/nidmresults.git@json_ld#egg=nidmresults
 - pip install -r requirements.txt
 # command to run tests, e.g. python setup.py test
script:  
- python TestSPMResultDataModel.py
- cat debug.log
before_install: 
 - git config --global user.name "TravisCI"
 - git config --global user.email "travis@dummy.com"
 